apiVersion: apps/v1
kind: Deployment
metadata:
  name: irmgard-worker
  namespace: irmgard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: irmgard-worker
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: irmgard-worker
    spec:
      containers:
        - name: worker
          image: docker.io/hofmanna9s/irmgard-worker:0.0.1
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: irmgard-worker
